tpcm/tpcm/urls.py
from django.contrib import admin
from django.urls import include, path
from tpcm_app import views

urlpatterns = [
    path('tpcm_app/', include('tpcm_app.urls')),
    path('admin/', admin.site.urls),
]
handler404 = views.custom_404
handler500 = views.custom_500

tpcm/tpcm_app/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_company = models.BooleanField(default=False)

class Student(models.Model):
    dept_choices = (('CS','CS'), ('EE','EE'), ('ME', 'ME'), ('CB', 'CB'), ('CE','CE'))
    course_choices = (('B.Tech','B.Tech'), ('M.Tech','M.Tech'), ('M.Sc','M.Sc'))
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name=models.CharField(max_length=30)
    cpi=models.DecimalField(max_digits=4,decimal_places=2, default='0')
    dept=models.CharField(max_length=30,default='-', choices=dept_choices)
    course=models.CharField(max_length=30,default='-', choices=course_choices)
    resume=models.URLField()
    webmail = models.EmailField(max_length=100, unique=True)
    avatar = models.ImageField(upload_to='images/', default='images/default.png')
    email = None

    def __str__(self):
        return self.name


class Company(models.Model):

    Category_choices=(('A1','A1'),('A2','A2'),('B1','B1'),)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=30)
    category = models.CharField(max_length=2,default='B1',choices=Category_choices)
    hr_name = models.CharField(max_length=30,default='-')
    hr_contact = models.EmailField(max_length=100,unique=True)
    sector = models.CharField(max_length=30, default='IT')
    email = None

    def __str__(self):
        return self.name

class JobPosition(models.Model):

    class Meta:
        unique_together=(('cmp_name','pos_name'),)

    dept_choices = (('CS','CS'), ('EE','EE'), ('ME', 'ME'), ('CB', 'CB'), ('CE','CE'))
    course_choices = (('B.Tech','B.Tech'), ('M.Tech','M.Tech'), ('M.Sc','M.Sc'))

    pos_name=models.CharField(max_length=30,help_text="This is the grey text")
    branch_appl=models.CharField(max_length=30,choices=dept_choices)
                                       
    cpi_req=models.DecimalField(max_digits=4,decimal_places=2, default='0')
    course_appl=models.CharField(max_length=30,choices=course_choices)                      
    stipend=models.IntegerField(null=True)
    ctc=models.IntegerField(null=True)
    test_date=models.DateField(null=True)
    cmp_name=models.ForeignKey(Company,on_delete=models.CASCADE,null=True)
    job_desc=models.CharField(max_length=800,null=True)
    def __str__(self):
        return self.id

class Application(models.Model):
    app_date = models.DateField(null=True)
    pos = models.ForeignKey(JobPosition, on_delete=models.CASCADE,null=True)
    stud = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    stat = models.IntegerField(default=0)
    def __str__(self):
        return self.id
    class Meta:
         unique_together=(('pos','stud'),)

tpcm/templates/company/compbase.html
<!DOCTYPE html>

<html lang="en">
	<head>
        <meta charset="utf-8">
        <title>TPC Management System</title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="/static/bootstrap.min.js"></script>
		<script src="/static/SmoothScroll.js"></script>
        <script src="/static/theme-scripts.js"></script>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="/static/logo.png">
		<!-- Bootstrap core CSS -->
		<link href="/static/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<!-- Custom styles for this template -->
        <link href="/static/style.css" rel="stylesheet">
		<link href="/static/btns.css" rel="stylesheet">
		<!-- jquery for date -->
		<link rel=”stylesheet” href=”//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css”>
	<link rel=”stylesheet” href=”/resources/demos/style.css”>
	<script src=”https://code.jquery.com/jquery-1.12.4.js”></script>
	<script src=”https://code.jquery.com/ui/1.12.1/jquery-ui.js”></script>
	<script>
		<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
	</script> 
	<script>
	$( function() {
	$( “#id_test_date” ).datepicker();
	} );
	</script>  
	</head>
	<style>
			body {
		
		background-color: #ffecd2 ; /* For browsers that do not support gradients */
  		background-image: linear-gradient(to right, #ffecd2  , #fcb69f); /* Standard syntax (must be last) */
	}
	img {
		opacity: 0.85;
		filter: alpha(opacity=44); /* For IE8 and earlier */
		display: block;

        height: 150px;
	}
	h2{
		font-weight:270;
	}
    h3{ 
    position: absolute; 
    top: 200px; 
    left: 0; 
    width: 100%; 
    }
	

	</style>
	
	<body id="page-top">

		<!-- Navigation -->
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
			
				<!-- Brand and toggle get grouped for better mobile display -->
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">

						<li>
							<a class="page-scroll" href="/tpcm_app/">Home</a>
						</li>
                        <li>
                                <a class="page-scroll" href="/tpcm_app/company/createjob">Create Position</a>
                        </li>
						<li>
                                <a class="page-scroll" href="/tpcm_app/company/positions">Positions</a>
                        </li>
						<li>
                                <a class="page-scroll" href="/tpcm_app/company/application">Applications</a>
                        </li>
                        <li>
                                <a class="page-scroll" href="/tpcm_app/company/profile"> {{username}}</a>
                         </li>
						<li>
							<a class="page-scroll" href="/tpcm_app/signout/">Sign out</a>
						</li>
					</ul>
                </div >
                <!-- /.navbar-collapse -->
				
		</nav>
	</body>
	<li>
				<a ><img src="/static/logo.png" class="center" ></a>
			</li>
	<div>
		<h3>
		{% block body %}
		{% endblock %}
		</h3>
	</div>
</html>

tpcm/templates/company/comphome.html
{% extends 'company/compbase.html' %}

{% block body %}
	<body id="page-top">
		<section id="portfolio">
			<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<div class="section-title">
						<div style="position:relative;">
							<h1>WELCOME TO TPC MANAGEMENT SYSTEM</h1>
							<p class="normal">This is a portal to easily manage TPC activities for both students and companies.</p>
						</div>
					</div>
				</div>
			</div>
		</section>
	</body>
{% endblock %}

tpcm/templates/company/createjob.html
{% extends 'base.html' %}

{% block title %}Create Job Position{% endblock %}

{% block body %}
<style>
        .button {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        padding: 16px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        -webkit-transition-duration: 0.4s; /* Safari */
        transition-duration: 0.4s;
        cursor: pointer;
    }
    .button2 {
    background-color: white; 
    color: black; 
    border: 2px solid #008CBA;
}
        

        </style>
<div style="position:relative; left:370px; bottom:50px">
        <div class="container">
            <form method="post">
                    {% csrf_token %}
                    {{ form.as_p}}

                    {% for value, text in form.branch_appl.field.choices %}
                        <div class="ui slider checkbox">
                            <input id="id_branch_appl_{{ forloop.counter0 }}" name="{{ form.branch_appl.name }}" 
                            type="checkbox" value="{{ value }}"{% if value in checked_branch_appl %} checked="checked"{% endif %}>
                            <label>{{ text }}</label>
                        </div>
                    {% endfor %}

                    <button class="button button2" type="submit">Create Position</button>

            </form>
        </div>
</div>
    
        
    

{% endblock %}